tiiuae/ci-test-automation

drcontrol/LICENSE, drcontrol/README.md, drcontrol/drcontrol.nix, drcontrol/drcontrol.py, drcontrol/flake.lock, drcontrol/flake.nix, drcontrol/orin_recovery_mode.sh, drcontrol/python requirements, drcontrol/setup.py
Add scripts for controlling relay board
to get Nvidia Orin to recovery mode.
=> Add scripts for controlling relay board

Jenkinsfiles/nuc_x86_test_set, Jenkinsfiles/orin_arm_test_set
Jenkinsfiles changes for flashing USB drive
for booting Orin from that.
=> Orin test automation with USB boot

Jenkinsfiles/nuc_x86_test_set
Add auto naming for Jenkins by top level Jenkins directory for triggerin right Jenkins jobs
=> Auto naming Jenkins jobs in jenkinsfiles

.github/workflows/check-commit.yaml, README.md, githooks/check-commit.sh, githooks/check-commits.sh, install-hooks.sh
Also updated readme and added github actions for checking commits.
=> Add githooks for checking commit messages

Robot-Framework/lib/output_parser.py, Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/apps.robot, Robot-Framework/test-suites/netvm.robot
Added 2 automated tests NetVM
1. Verify that NetVM stops properly and starts after that (SP-T52)
2. Verify that created file will be removed after restarting VM (SP-T53)
Also made a refactoring of keywords for NetVM managing
Signed-off-by: Mariia Azbeleva <mariia.azbeleva@unikie.com>
=> Added two automated tests of restarting NetVM

Robot-Framework/lib/output_parser.py, Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/boot_test.robot
1. Refactor ghaf version tests: Its version doesn't suppose to match Nixos version
2. Add nixos version test
=> Nixos and ghaf versioning tests

Robot-Framework/lib/output_parser.py, Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/apps.robot, Robot-Framework/test-suites/netvm.robot
Make find all running process with exact name
=> Fix method of looking for the running process

Robot-Framework/config/variables.robot
Change netvm service name to netvm.service due to changes in Ghaf
=> Change netvm service name

Robot-Framework/resources/serial_keywords.resource, Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/bat-tests/__init__.robot, Robot-Framework/test-suites/bat-tests/apps.robot, Robot-Framework/test-suites/bat-tests/netvm.robot, Robot-Framework/test-suites/bat-tests/others.robot, Robot-Framework/test-suites/boot_test.robot
1. Add more log messages to console
2. Add saving and printing of versions ang journalctl
3. Move version tests to another suite
4. Add checking of port 22 of netvm
=> Add logging and additional checks

Jenkinsfiles/orin_arm_test_set
Change booting device name for ORIN
=> Change booting device name for ORIN

Jenkinsfiles/nuc_x86_test_set, Jenkinsfiles/orin_arm_test_set
There was mentioning of "Spectrum" in name of stage
=> Fix jenkins stage naming

Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/bat-tests/netvm.robot, requirements
1. Check that wpa_supplicant.service exists and is started:
- as a separate test
- as a condition for wifi passthrough test
2. Retry Wifi test once if failed to avoid occasioanl problem with a network
=> Verify wpa_supplicant status

Robot-Framework/config/variables.robot, Robot-Framework/lib/PerformanceDataProcessing.py, Robot-Framework/lib/output_parser.py, Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/performance/performance.robot, requirements
**!! Can't be merge before sysbench is added to Ghaf.**
Add performance tests for CPU and Memory which doesn't actually have expected results, but execute tests, save results in csv files on Jenkins machine and build plots comparing metrics with previous builds.
Example:
=> Add performance tests

Robot-Framework/config/variables.robot, Robot-Framework/test-suites/bat-tests/netvm.robot
Change netvm to net-vm, set it as a variable
=> Change netvm name

Jenkinsfiles/hw_test_set
Changes for using zipped Orin images to flash
HW test device.
=> Changes for using Orin zipped images

Jenkinsfiles/hw_test_set
Add fix for falshing Orin devices with zipped images.
=> Fix for flashing zipped images

Jenkinsfiles/hw_test_set
Run performance HW tests if boot test is succesfully completed.
=> Run performance tests if boot test OK

Robot-Framework/resources/serial_keywords.resource, Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/bat-tests/others.robot, Robot-Framework/test-suites/boot_test.robot
1. Check init `systemctl status init.scope` instead of `systemctl status`
2. Move checking `systemctl status` to the dedicated test
=> Refactor boot test

Robot-Framework/test-suites/bat-tests/others.robot
No VMs and Browser tests for Polarfire
=> Add riscV tag

Robot-Framework/resources/serial_keywords.resource
=> Check init state via serial connection

Jenkinsfiles/hw_test_set
Fix zipped image flashing how it was
simplified solution not seems to work correctly
=> Fix zipped image flashing

Jenkinsfiles/hw_test_set, Robot-Framework/config/variables.robot, Robot-Framework/lib/SwitchbotLibrary.py, Robot-Framework/test-suites/bat-tests/apps.robot, Robot-Framework/test-suites/bat-tests/netvm.robot, Robot-Framework/test-suites/bat-tests/others.robot, Robot-Framework/test-suites/boot-test/boot_test.robot, Robot-Framework/test-suites/performance-tests/network.robot, Robot-Framework/test-suites/performance-tests/performance.robot, Robot-Framework/test-suites/report.html
To support this PR, the following changes should be done in  Jenkins pipeline:
1. run boot test using tags: bootAND${params.device} because for lenovoX1 it will be the another test case:
1.1. this tag is provided by hw_test_set jenkins file as a value of the variable INCLD_TAG 
1.2. the string parameter INCLD_TAG should be created in the boot_test job
1.3. the parameter INCLD_TAG should be used in run command: -i $INCLD_TAG
2. Button pressers need secret token and password, which should be secretly provided from run command
2.1. secret 'password' parameters SWITCH_TOKEN and  SWITCH_SECRET should be created in the boot_test job
2.2. these parameters should be used in run command:  -v SWITCH_TOKEN:$SWITCH_TOKEN -v SWITCH_SECRET:$SWITCH_SECRET
=> Add boot test for LenovoX1

Jenkinsfiles/hw_test_set, Robot-Framework/resources/serial_keywords.resource, Robot-Framework/test-suites/boot-test/boot_test.robot
Turning OFF test is run now after the end of all tests as a last stage of hw_test_set pipeline, in any case.
Also created Turning ON test and jenkins job for it which can be run manually if needed
=> Add stage for turning off device

Jenkinsfiles/ghaf_infra_hw_test_set
Add ghaf_infra_hw_test_set Jenkinsfile
ONLY runs boot test for Orin AGX for now.
=> Add ghaf-infra HW test set

Robot-Framework/lib/PerformanceDataProcessing.py, Robot-Framework/test-suites/performance-tests/performance.robot
Change the test sequence so that it does not stop in case of failure in connecting one of the AppVMs
=> Continue test VMs if some of them fail

Robot-Framework/test-suites/bat-tests/apps.robot
Update Lenovo-X1 app names according to https://github.com/tiiuae/ghaf/pull/582.
This PR should be merged after https://github.com/tiiuae/ghaf/pull/582 has been merged.
=> Update app names for LenovoX1

Robot-Framework/lib/PerformanceDataProcessing.py, Robot-Framework/lib/performance_thresholds.py, Robot-Framework/resources/performance_keywords.resource, Robot-Framework/test-suites/performance-tests/network.robot, Robot-Framework/test-suites/performance-tests/performance.robot
Report test PASS/FAIL based on the actual results, not only based on success in running the test commands.
=> Add statistics and PASS/FAIL status based on change in result value to performance tests

Robot-Framework/lib/PerformanceDataProcessing.py, Robot-Framework/lib/performance_thresholds.py, Robot-Framework/resources/performance_keywords.resource, Robot-Framework/test-suites/performance-tests/network.robot, Robot-Framework/test-suites/performance-tests/performance.robot
Currently any significant deviation (also increase) will cause the test case to fail. With this change test case will not get failed status if the performance improves beyond threshold but only in case the performance decreases.
=> Fix test case fail criteria

Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/bat-tests/apps.robot
=> Check ssh on VMs before start apps

Robot-Framework/lib/PerformanceDataProcessing.py, Robot-Framework/lib/performance_thresholds.py, Robot-Framework/resources/common_keywords.resource, Robot-Framework/resources/device_control.resource, Robot-Framework/test-suites/boot-test/boot_test.robot, Robot-Framework/test-suites/performance-tests/boot_time_test.robot
Adding some measurements for soft reboot and hard reboot.
=> SP-4660 Measure boot time

Robot-Framework/test-suites/boot-test/boot_test.robot
Add correct resource file to test
=> Add correct resouce file for keyword

Robot-Framework/test-suites/performance-tests/boot_time_test.robot
Update the text that is grepped from logging
=> Update waybar to ewwbar

Robot-Framework/test-suites/performance-tests/boot_time_test.robot
Remove performance tag in order to disable tests for now
=> Disable boottime perf tests

Robot-Framework/resources/performance_keywords.resource, Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/resources/virtualization_keywords.resource, Robot-Framework/test-suites/bat_test_nuc.robot, Robot-Framework/test-suites/performance-tests/boot_time_test.robot, Robot-Framework/test-suites/performance-tests/network.robot
Update Robot Framework Return-keyword to use newer style in order to get rid of warnings in RF logs
=> Update RF return keyword

Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/bat-tests/others.robot
Check actual storage size and check storagevm is showing correct size
=> SSRCP-5321 Check storage

Robot-Framework/test-suites/performance-tests/performance.robot
Remove date and server from file name
=> Update used file name format

Robot-Framework/resources/ssh_keywords.resource
Modify memory test to accept floats and integers.
Note, commit name is incorrect, this is about memory status check
=> Modify memory status test

Robot-Framework/test-suites/bat-tests/netvm.robot
We don't use it anymore for WiFI configuring
=> Remove wpa_supplicant test

Robot-Framework/config/variables.robot, Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/bat-tests/netvm.robot
Required changes in jenkinsfiles (needed to add variables TEST_WIFI_SSID and TEST_WIFI_PSWD)
=> Refactor wifi test

Robot-Framework/config/variables.robot, Robot-Framework/test-suites/bat-tests/apps.robot, Robot-Framework/test-suites/bat-tests/business_vm.robot, Robot-Framework/test-suites/gui-tests/gui_apps.robot, Robot-Framework/test-suites/performance-tests/performance.robot, pkgs/ghaf-robot/default.nix
Update Chromium to Chrome.
Add some tools to default.nix for gui tests
=> Update Chromium to Chrome

Robot-Framework/lib/PerformanceDataProcessing.py, Robot-Framework/test-suites/performance-tests/network.robot
=> Performance tests

Robot-Framework/config/variables.robot, Robot-Framework/resources/connection_keywords.resource, Robot-Framework/test-suites/bat-tests/netvm.robot, Robot-Framework/test-suites/logging-tests/check_logs.robot
Add test case for checking that all virtual machines are sending log data to Grafana
=> SP-T172 Check logs

Robot-Framework/config/variables.robot
Small fix to https://github.com/tiiuae/ci-test-automation/pull/172, chromium-vm has been changed to chrome-vm while that pr was open. The conflict is causing the tests to fail at least when I am running them manually.
=> Replace Chromium with Chrome

Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/bat-tests/business_vm.robot, Robot-Framework/test-suites/bat-tests/gui-vm.robot
Add basic tests for opening and closing applications
=> Add application tests

Robot-Framework/__framework__.resource, Robot-Framework/resources/common_keywords.resource, Robot-Framework/resources/connection_keywords.resource, Robot-Framework/resources/gui_keywords.resource, Robot-Framework/test-suites/bat-tests/__init__.robot, Robot-Framework/test-suites/video-tests/video.robot
Video tests
- Checking that camera is available only in business-vm
- Checking that video clip can be recorded, and some basic checks for video file is done
=> Add video tests

flake.nix
This is needed for running the logging test manually.
=> Add grafana-loki to flake.nix

Robot-Framework/test-suites/bat-tests/gui-vm.robot
Change name of the bluetooth process which should be used for shutting down process
=> Modify bluetooth process name in test

Robot-Framework/resources/gui_keywords.resource, Robot-Framework/test-suites/bat-tests/__init__.robot, Robot-Framework/test-suites/bat-tests/apps.robot, Robot-Framework/test-suites/gui-tests/__init__.robot, Robot-Framework/test-suites/performance-tests/performance.robot
Adapt also gui keywords to new test user
=> Log in and log out in bat init

Robot-Framework/test-suites/video-tests/video.robot
Create video files to /tmp folder
=> Fix video tests

Robot-Framework/test-suites/performance-tests/performance.robot, Robot-Framework/test-suites/performance-tests/sysbench_test
Added also fix for sysbench in VMs. Tested locally with few VMs that it works.
=> Change relative paths to absolute

Robot-Framework/test-suites/video-tests/video.robot
After https://github.com/tiiuae/ghaf/pull/939 is merged `sudo` will be needed with video tests. This pr adapts to that and fixes one small typo in documentation.
Can be merged before 939, works also with the current version.
=> Update video tests

KMTronic/README.md, KMTronic/kmtronic_4ch_control.py, KMTronic/kmtronic_4ch_status.py, README.md, Robot-Framework/config/variables.robot, Robot-Framework/lib/KMTronicLibrary.py, Robot-Framework/resources/device_control.resource, Robot-Framework/resources/serial_keywords.resource, Robot-Framework/test-suites/boot-test/relay_boot_test.robot
Add relay_boot_test.robot and needed keywords
to use relay for boot device by cutting down power.
Add KMTronic relay board control and status python scripts and README. Add also Robot framework library for KMTronic control.
=> Add relay_boot_test.robot

Robot-Framework/lib/KMTronicLibrary.py, Robot-Framework/resources/serial_keywords.resource
If port is 'NONE' do not open connection.
=> Add port check to KMTronicLibrary

Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/bat-tests/netvm.robot
Increased timeouts a bit to prevent fails caused by hurry.
=> Cleanup and tune netvm tests

Robot-Framework/config/variables.robot, Robot-Framework/resources/connection_keywords.resource, Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/bat-tests/check_logs.robot, Robot-Framework/test-suites/bat-tests/netvm.robot
PR https://github.com/tiiuae/ghaf/pull/915 could not yet be merged because of build issues. This PR will revert the changes added for that, these changes will be added back again later.
=> Revert "Update test connections"

Robot-Framework/resources/common_keywords.resource, Robot-Framework/resources/connection_keywords.resource, Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/bat-tests/netvm.robot, Robot-Framework/test-suites/bat-tests/others.robot, Robot-Framework/test-suites/boot-test/boot_test.robot, Robot-Framework/test-suites/gui-tests/gui_power_options.robot, Robot-Framework/test-suites/performance-tests/network.robot, Robot-Framework/test-suites/performance-tests/performance.robot
Fixes the remaining problems (mainly others test suite) on X1 after ethernet interface switched to net-vm.
=> More fixes after ghaf pr915

Robot-Framework/test-suites/bat-tests/others.robot
Old issue was fixed and a new bug found.
(Also fixes the NUC issue number)
=> Update Check systemctl status issue numbers

Robot-Framework/test-suites/bat-tests/check_logs.robot
Change MAC into device id at a different location.
=> Change id location

Robot-Framework/test-suites/performance-tests/performance.robot
Previously used gp_storage is no more available.
=> Run fileio tests in /persist

Robot-Framework/test-suites/bat-tests/apps.robot
Relates to issue https://jira.tii.ae/browse/SSRCSP-6434
=> Add skip for Gala if it fails

Robot-Framework/lib/ParsePowerData.py, Robot-Framework/resources/power_meas_keywords.resource, Robot-Framework/test-suites/gui-tests/gui_power_options.robot
report.html file link to power plot has been broken after changing to path variables. Fix the problems.
=> Fix path for power plot

Robot-Framework/resources/device_control.resource
LenovoX1:
boot test if the laptop was UP before:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/949/
boot test if the laptop was DOWN before: 
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/950/
Dell7330:
boot test if the laptop was UP before: 
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/952/
boot test if the laptop was DOWN before:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/951/
=> Turn off laptops without conditions

Robot-Framework/test-suites/bat-tests/apps.robot
Issue has been rejected since it has not been seen in a while https://jira.tii.ae/browse/SSRCSP-5385
Let's remove the skip and see if we can see any fails.
=> Remove skip from Zathura test

Robot-Framework/resources/gui_keywords.resource, Robot-Framework/test-suites/gui-tests/gui_apps.robot
1st thought that this is some timing issue -> added iterations selection up to the test case -level.
Then discovered that there seems to be bug around and created a ticket & added skip for the test in case of failure.
Test Result: https://ghaf-jenkins-controller-prod.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/153/
=> Add Test Case skip and iterations change

Robot-Framework/test-suites/bat-tests/gui-vm.robot
Should be merged at the same time with https://github.com/tiiuae/ghaf/pull/1104
Small change to the name of the Control Panel.
[Test run](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/ghaf-hw-test/775/)
=> Update Control Panel name

Robot-Framework/test-suites/suspension-test/suspension.robot
Brightness values were changed. Now we are getting the maximum value from /sys and calculating the dimmed value as 25% of maximum.
Also added power measuring during suspension time
test run:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1066/
=> Change brightness in suspension test

Robot-Framework/resources/common_keywords.resource, Robot-Framework/test-suites/bat-tests/gui-vm.robot, Robot-Framework/test-suites/suspension-test/suspension.robot
test on Dell:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1429/
test on Lenovo:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1432/
=> Add Falcon AI test

Robot-Framework/test-suites/bat-tests/gui-vm.robot, Robot-Framework/test-suites/suspension-test/suspension.robot
Added waiting for notification that Download was completed before check that app is started
Dell:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1503/
LenovoX1:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1501/
=> Wait until Falcon download complete

Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/bat-tests/apps.robot
Dell:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1575/
LenovoX1:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1574/
LenovoX1 Cosmic:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1573/
=> Add open image test

Robot-Framework/lib/PerformanceDataProcessing.py
Show the actual threshold parameter which has been used for calculating pass marginals in each performance plot (excluding bar charts from VMs).
Added missing title for iperf plot.
=> Show threshold value on performance plot

Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/functional-tests/gui-vm.robot
LenovoX1:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1710/
Dell7330:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1711/
=> Check systemctl status for user

Robot-Framework/test-suites/functional-tests/gui-vm.robot
X1
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1805/
Cosmic:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1806/
Dell7330:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1807/
=> Add checking Falcon model

Robot-Framework/test-suites/functional-tests/video.robot, list_of_skipped_tests.md
This seems to fail too often, skip the case until the root cause for problems are understood/solved. 
Ticket: SSRCSP-6694
Test  result: [Dev#1964](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1964/)
=> Skip randomly failing Video case (Dell)

Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/functional-tests/apps.robot
Dell7330
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2040/
LenovoX1
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2039/
=> Add test file opening test

Robot-Framework/test-suites/gui-tests/gui_apps.robot
[Lenovo-X1](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2041/)
=> Add GUI Sticky Notes test back

Robot-Framework/test-suites/functional-tests/apps.robot, Robot-Framework/test-suites/functional-tests/audio.robot, Robot-Framework/test-suites/functional-tests/gui-vm.robot, Robot-Framework/test-suites/functional-tests/host.robot
Also add Sticky Notes test back, it was fixed on Cosmic.
[Dell-7330](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2294/)
[Orin-AGX
](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2295/)
I tested Lenovo-X1 locally, it is the same tests than with Dell-7330.
=> Add more pre-merge tests

Robot-Framework/lib/output_parser.py, Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/functional-tests/vm.robot
[Lenovo-X1](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2312/)
[Dell-7330](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2314/)
=> Remove skip from VM systemctl check

Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/functional-tests/apps.robot
General keyword for opening PDF from vm.
In addition to chrome-vm, test cases for opening PDF from comms-vm, business-vm and gui-vm.
=> More test cases for opening PDF

Robot-Framework/resources/ssh_keywords.resource
LenovoX1, affected tests:
apps https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2454/
businessvm,shares https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2455/
=> Refactor file exists keyword

Robot-Framework/resources/gui_keywords.resource
https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/53/
=> Add Dell extra time before verifying login

Robot-Framework/lib/PerformanceDataProcessing.py
Occasional close-to-zero results have led to situations where lower_marginal is higher than upper_marginal. With such pass limits it is impossible to pass the test.
Prevent this happening by removing secondary pass/fail criteria based on the deviation from the first measurement of the baseline period. This allows slow monotonic change over threshold without test automation flagging it failure.  
Renamed a variable for clarity.
Original plot (https://ci-prod.vedenemo.dev/job/ghaf-hw-test/976/artifact/Robot-Framework/test-suites/performance/LenovoX1-1_Measure%20UDP%20Bidir%20Throughput%20Big%20Packets.png) with awkward marginals in the receiving speed section (sometimes upper_marginal < lower_marginal)
Locally re-run the test with the same measurement history (csv file copied from prod …
=> Fix bug in marginal calculation

Robot-Framework/test-suites/suspension-test/suspension.robot
https://github.com/tiiuae/ghaf/pull/1244 changed how the suspension works
[Testrun](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/549/)
=> Fix suspension test

Robot-Framework/test-suites/functional-tests/net-vm.robot
Noticed that AGXs file creation & check needs to be done with sudo. Originally sudo was used in test, but due to failure skip set  in that specific test, this was not captured  when some re-factoring was done
Also added specific SKIP check if possible failure is due to the known connection issue or not.
[Test result all passing](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/592/artifact/Robot-Framework/test-suites/orin-agx-64ANDnet-vm/log.html)
[Test result for test skipping](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/593/artifact/Robot-Framework/test-suites/orin-agx-64ANDnet-vm/log.html)
=> Add sudo for file operations and Refactor AGX skip investigation

Robot-Framework/resources/gui_keywords.resource
[Testrun](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/617/)
=> Return lock icon

Robot-Framework/resources/gui_keywords.resource, Robot-Framework/test-suites/gui-tests/input_control.robot
test run: [Lenovo-X1](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/694/artifact/Robot-Framework/test-suites/SP-T134/log.html)
all gui tests: https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/701/artifact/Robot-Framework/test-suites/guiANDlenovo-x1/log.html
=> Add audio control test

Robot-Framework/test-suites/functional-tests/timesync.robot
Created 2 separated tests:
1. for Gui-VM only - run in BAT tests
2. for all VMs including GuiVM - run in regression tests
Test runs:
[Lenovo X1](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/714/artifact/Robot-Framework/test-suites/timesync/log.html)
[Dell](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/715/artifact/Robot-Framework/test-suites/timesync/log.html)
=> Add time tests for all VMs

Robot-Framework/resources/ssh_keywords.resource, Robot-Framework/test-suites/functional-tests/host.robot, Robot-Framework/test-suites/functional-tests/net-vm.robot, Robot-Framework/test-suites/functional-tests/optee.robot, Robot-Framework/test-suites/functional-tests/timesync.robot
Orin NX https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/791/
Orin AGX https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/790/
=> Decrease amount of connections

Robot-Framework/resources/device_control.resource
Tested in production
- Dell-7330 https://ci-prod.vedenemo.dev/job/ghaf-hw-test-manual/99/
- Lenovo-X1 https://ci-prod.vedenemo.dev/job/ghaf-hw-test-manual/100/
=> Shorten time between off and on presses

Robot-Framework/resources/device_control.resource, Robot-Framework/test-suites/boot-test/relay_boot_test.robot
Lenovo X1
Was ON before https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/958/ - started from 1st attempt
Was OFF before https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/960/ - started from 1st attempt
Dell
Was ON before https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/959/ - started from 1st attempt
Was OFF before https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/961/ - started from 2nd attempt
=> Try turn on laptop one more time

Robot-Framework/test-suites/gui-tests/gui_apps.robot, list_of_skipped_tests.md
Bug fixed in https://github.com/tiiuae/ghaf/pull/1348
[Testrun](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1125/)
=> Remove GUI Chrome skip

Robot-Framework/resources/common_keywords.resource, Robot-Framework/test-suites/functional-tests/host.robot, Robot-Framework/test-suites/functional-tests/vm.robot
Memory managers keep randomly failing on all laptops, latest example here https://ci-prod.vedenemo.dev/job/ghaf-hw-test/5610/
[Testrun](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1431/)
=> Extend ghaf-mem-manager skip to all devices

Robot-Framework/test-suites/security-tests/firewall.robot
test runs:
[DarterPRO](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1559/artifact/Robot-Framework/test-suites/SP-T288/log.html)
[LenovoX1](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1562/artifact/Robot-Framework/test-suites/SP-T288/log.html)
[Dell7330](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1567/artifact/Robot-Framework/test-suites/SP-T288/log.html)
=> Add VM firewall test
