Robot-Framework/config/variables.robot

Error in the config parsing caused revealing of the file content in logs. 
Adding catching of Error and failing with custom error message will help to avoid revealing of sensetive data

Catch JSONDecodeError

---

Robot-Framework/lib/output_parser.py
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/boot_test.robot

Check that ghaf-version contains the date of commit in format yyyymmdd, 7 symbols of hash commit and returns the same NixOS version as the command "nixos-version"
Signed-off-by: Mariia Azbeleva <mariia.azbeleva@unikie.com>

Add autotest for Ghaf versioning

---

README.md
Robot-Framework/default.nix
flake.lock
flake.nix
pkgs/PyP100/default.nix
pkgs/ghaf-robot/default.nix
pkgs/pkcs7/default.nix
pkgs/robotframework-advancedlogging/default.nix
pkgs/robotframework-seriallibrary/default.nix

This flake provides a wrapper `ghaf-robot` script to run Robot Framework in an environment where all the required dependency Python modules are present. Additionally few required Python library packages are provided, and also devshell environment is provided.

Flake and ghaf-robot wrapper script for running the Robot Framework test suites on Nix/NixOS

---

Robot-Framework/lib/PlugLibrary/PlugLibrary.py
Robot-Framework/lib/PlugLibrary/TapoP100v2.py

TapoP100 plugs can have different HW versions. Plugs with HW ver 2.0 use the another protocol which is not supported by PyP100 pythin library. So library plugp100 will be used for those plugs. 
PyP100 is still used by default, To use plugp100 it's needed to define variable  **-v PLUG_TYPE:TAPOP100v2** 
plugp100 can be also used for HW ver 1.x.

Use tapop100 lib for Tapo Plugs HW ver2

---

Robot-Framework/test-suites/performance/performance.robot

There is no need to install sysbench because now it is included to ghaf.

[SP-3141] Remove installing sysbench tool

---

Robot-Framework/test-suites/bat-tests/netvm.robot

Remove all dead code and unnecessary SSH key generation, and create SSH local port forward directly from test machine to the NetVM's SSH port, instead of doing localhost port forwarding inside the remote host being tested. (`sudo su` is also pointless in general, better use `sudo -s`.)

netvm.robot: Cleanup establishing of NetVM tunnel

---

Robot-Framework/resources/virtualization_keywords.resource
Robot-Framework/test-suites/bat-tests/netvm.robot
flake.lock

netvm.robot: Test which checks PCI passthrough devices are visible inside NetVM
Tested on both Orin AGX and NUC. Should also work with Orin NX.
Generic test which reads from microvm's configuration which PCI devices are supposed to be passed through, and then checks are they really visible inside the microvm using `lspci`.

netvm.robot: Test which checks PCI passthrough devices are visible inside NetVM

---

Robot-Framework/test-suites/bat-tests/netvm.robot

This fixes the randomly appearing "OSError 98 Address already in use" from the later test's setup phase.

SP-T50: fix teardown

---

Robot-Framework/test-suites/bat-tests/netvm.robot

Use of local port forwards turned out to be flaky because of issue in the Robotframework's SSHLibrary (https://github.com/robotframework/SSHLibrary/issues/435 https://github.com/robotframework/SSHLibrary/pull/436). Use SSH's jumphost feature instead, which is anyway much simpler, and does not require reserving local ports.

netvm.robot: Use jumphost instead of port forward

---

Robot-Framework/test-suites/performance/network.robot

Ensure that process was started and wait a bit if needed. For some devices it can take longer time to start this process.

Check if iperf server was started

---

Robot-Framework/config/variables.robot
Robot-Framework/lib/output_parser.py
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/bat-tests/apps.robot
Robot-Framework/test-suites/bat-tests/netvm.robot
Robot-Framework/test-suites/bat-tests/others.robot

Add tag for LenovoX1 target, refactored Browser test

Add LenovoX1 target

---

Jenkinsfiles/hw_test_set

Add polarfire flashing via USB-SD-MUX

Polarfire SD-MUX flashing

---

Jenkinsfiles/hw_test_set
Robot-Framework/config/variables.robot
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/bat-tests/apps.robot

RobotFramework will skip browser test if the tested build doesn't contain applications (based on the name of the job):
Test run commant must contain the number of the tested build _-v BUILD_ID:$BUILD_ID_ (in Jenkins pipline it must be provided by the parent job)
config directory should contain $BUILD_ID.json
with the name of the job, for example:
```
{
"Job": "nvidia-jetson-orin-agx-debug-nodemoapps-from-x86_64.x86_64-linux"
}
```

[SP-3404] Skip browser test if the tested build doesn't contain apps

---

Robot-Framework/test-suites/bat-tests/optee.robot

Initial pkcs11-tool tests for OP-TEE, test OP-TEE's PKCS#11 both by:
* Calling OP-TEE directly
* Calling OP-TEE through caml-crush's pkcs11proxyd

Initial pkcs11-tool tests for OP-TEE

---

flake.lock
flake.nix

• Updated input 'nixpkgs':
'github:nixos/nixpkgs/e9f06adb793d1cca5384907b3b8a4071d5d7cb19'
(2023-12-03)
→ 'github:nixos/nixpkgs/b4372c4924d9182034066c823df76d6eaf1f4ec4'
(2023-12-07)

Switch nixpkgs flake input to NixOS 23.11

---

Jenkinsfiles/hw_test_set

Supplementary PR for https://github.com/tiiuae/ci-public/pull/226
Requires manual changes to smoke_tests and performance_tests jobs in production to add new `RESULTS_PATH` variable and use it. (copy from development side)

Use new location of buildid.json

---

Robot-Framework/lib/output_parser.py
Robot-Framework/resources/serial_keywords.resource
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/bat-tests/__init__.robot

If test config contains empty IP address for device than Robot will try to connect via serial and get IP address from ifconfig output and use it for bat tests

[SP-3721] Get IP address via serial

---

flake.nix
pkgs/ghaf-robot/default.nix

`pytz` was missing from dependencies, so added it

Add missing pytz dependency to .nix files

---

Robot-Framework/lib/output_parser.py
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/bat-tests/apps.robot

Support for parsing Exec command paths from XDG .desktop files, that are used with the nwg-drawer used within LabWC edition of Lenovo X1 build.

LabWC support for application launch tests

---

Robot-Framework/lib/PerformanceDataProcessing.py
Robot-Framework/test-suites/performance-tests/network.robot
Robot-Framework/test-suites/performance-tests/performance.robot

Add build type to performance report

---

Robot-Framework/test-suites/bat-tests/optee.robot

Adjust OP-TEE xtests to match jetpack-nixos update in ghaf's flake.lock
To match this PR: https://github.com/tiiuae/ghaf/pull/561

Adjust OP-TEE xtests to match jetpack-nixos update

---

Robot-Framework/resources/ssh_keywords.resource

Add prompt argument to SSHLibrary's Open Connection calls. This makes the SSH connection succeed even if it takes more than 0.5 seconds for the actual prompt to appear after SSH connection has been established, and it will also make test faster if it appears earlier.
I wanted to add this because I started to have problems because it started to take more than 0.5 seconds for the actual prompt to appear, and then the connection failed on the "Should Contain" -keyword, because it did not contain the prompt
http://robotframework.org/SSHLibrary/SSHLibrary.html#Login
Here it says "If the [prompt](http://robotframework.org/SSHLibrary/SSHLibrary.html#Prompt) is set, everything until the prompt is read. Otherwise the output is read using the …

Add prompt argument to Open Connection calls

---

Robot-Framework/test-suites/performance-tests/fileio_test
Robot-Framework/test-suites/performance-tests/performance.robot

Disk space on Lenovo-X1 ghaf-host has been reduced. Directory /home/ghaf doesn't have anymore enough disk space for running the fileio read test (required more disk space than memory). However ghaf-host has now multiple mountpoints of which /gp_storage is suitable for running the test (50G disk space). Change to that directory for creating test files and running the test.
Improve also test reporting in case there is not enough disk space.

Run fileio test in /gp_storage on Lenovo-X1 target

---

Robot-Framework/test-suites/performance-tests/fileio_test
Robot-Framework/test-suites/performance-tests/performance.robot

Since nvpmodel check is applicable only for Orin AGX/NX targets remove it from fileio_test script which is common for all targets. Create a new test for nvpmodel check and run it only on Orin targets. Use the helper script integrated into ghaf: 
https://github.com/tiiuae/ghaf/blob/main/modules/common/development/scripts/nvpmodel_check.nix
Also remove "-X1" from the fileio test device name criteria because there is some variation in the format of the device name among testers (LenovoX1-1, Lenovo-X1...)

Refactor nvpmodel check to be a separate test

---

Robot-Framework/test-suites/bat-tests/others.robot

Skip test in case if test fails because issue is known but has low priority.

Skip systemctl status test for NUC

---

Robot-Framework/config/variables.robot
Robot-Framework/lib/PerformanceDataProcessing.py
Robot-Framework/lib/performance_thresholds.py
Robot-Framework/test-suites/bat-tests/apps.robot
Robot-Framework/test-suites/performance-tests/performance.robot

In ghaf PR724 element-vm is changed to comms-vm and also Slack App is added to the VM. With these fixes the element launch test (kill processes part) survives the changes. Added also launch test for the new Slack App.
In addition created separate lenovo-x1 specific performance threshold parameter for fileio read test because lenovo-x1 fileio rd test results jumped very high few weeks ago causing also variance of the results to increase compared to other targets. So assigning a larger threshold for this specific test/target was appropriate.

Apply changes introduced by ghaf PR724

---

Robot-Framework/lib/performance_thresholds.py

Based on accumulated test results we have now better understanding of the level and variance of different performance test results. Here thresholds are harmonized so that each threshold is set to value at least five times the largest standard deviation calculated from the stable periods.
Thresholds could be specified also separately for each VM but for now it seems it's not necessary.

Adjust performance test thresholds

---

Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/bat-tests/apps.robot

- Log journalctl for each vm after test
- remove 'bat' tag for Appflowy test

Add logging for each vm

---

Robot-Framework/test-suites/performance-tests/boot_time_test.robot

Update test to search different word from journalctl

Update Boot time test

---

Robot-Framework/resources/ssh_keywords.resource

Modify ghaf version check test

Modify version checking

---

Robot-Framework/test-suites/bat-tests/business_vm.robot

Trusted Browser is not related to Microsoft. Removed Microsoft from the name.

Fix Trusted Browser name

---

Robot-Framework/lib/PerformanceDataProcessing.py
Robot-Framework/lib/performance_thresholds.py
Robot-Framework/test-suites/bat-tests/timesync.robot
Robot-Framework/test-suites/performance-tests/performance.robot

Fixed wrong variable name. Added target specific thresholds for NUC since it has higher deviation in cpu/mem results than other targets.
Also minor correction to keyword 'Check that time is correct'

Fix sysbench test in NetVM

---

Robot-Framework/test-suites/bat-tests/apps.robot

Appflowy was removed from Lenovo-X1 so no need to keep the tag. The tag makes running the tests manually more complicated.

Remove lenovo-x1 tag from Start Appflowy test

---

Robot-Framework/resources/gui_keywords.resource
Robot-Framework/test-suites/gui-tests/__init__.robot

Once ghaf PR#888 goes in this needs to be merged for gui tests suite to work.
This includes also a bug fix: 
Unlock -> GUI Unlock 
in __init__.robot

Switch to papirus theme

---

Robot-Framework/test-suites/bat-tests/apps.robot

gui_testing.py was causing module not found error. If the error arises when gui test suite is included it should be dealt with.

Remove unnecessary libraries

---

Robot-Framework/test-suites/gui-tests/gui_apps.robot

The firefox open/close gui test cannot pass as long as Orin AGX does not have a display connection in the test setup. Prevent running this test in the pipeline.
GUI test suite was just added to the nightly pipeline.

Remove orin-agx tag from the firefox gui test

---

Robot-Framework/config/variables.robot

These changes require to have on test running machine test files which contains some secret parameters:
/run/secrets/dut-pass
/run/secrets/plug-login
/run/secrets/plug-pass
/run/secrets/switch-token
/run/secrets/switch-secret
/run/secrets/wifi-ssid
/run/secrets/wifi-password

Read secrets from agent

---

Robot-Framework/test-suites/performance-tests/network.robot

Add timeout to Run Process keyword to prevent jamming in performance tests
Remove old perf-tets

Add timeout to process keyword

---

Robot-Framework/config/variables.robot
Robot-Framework/resources/gui_keywords.resource
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/bat-tests/__init__.robot
Robot-Framework/test-suites/bat-tests/apps.robot
Robot-Framework/test-suites/bat-tests/business_vm.robot
Robot-Framework/test-suites/bat-tests/gui-vm.robot

Adapting ci-test-automation to the changes introduced by ghaf PR#827

Adapt to changes introduced by ghaf PR827

---

Robot-Framework/test-suites/bat-tests/apps.robot

There were some temporary changes merged accidentally in fabe54b0e471e858f3ad181b2d3366ffdfc2681e. Revert them back to previous state.

Revert apps.robot to it's pervious state

---

Robot-Framework/test-suites/audio-tests/audio.robot
flake.nix
pkgs/ghaf-robot/default.nix

Add audio tests to ci
This pr need also another pr approved on ghaf side 
https://github.com/tiiuae/ghaf/pull/934

Add audio tests

---

Robot-Framework/test-suites/performance-tests/fileio_test
Robot-Framework/test-suites/performance-tests/performance.robot

Used https://github.com/tiiuae/ci-test-automation/pull/191 as the starting point.
Notes:
- Each Execute Command keyword run in a new shell. So doing cd on one Execute Command line does not affect the working directory of another Execute Command line. However, with Write it remains in the same shell.
- Had to Read Until "Test finished.". Read Until Prompt didn't work for some reason.
- Had to increase timeout temporarily for Read Until. For now I set it to 15min (and then back to 30s), should be enough as on my local test runs the fileio test took 4.5 minutes.

Fix sysbench fileio test

---

Robot-Framework/resources/gui_keywords.resource
Robot-Framework/test-suites/gui-tests/gui_apps.robot

Added also temporary fix for Verify login keyword (to run grim as testuser and login as ghaf before return)

Add GUI launch test for PDF Viewer

---

Robot-Framework/resources/gui_keywords.resource
Robot-Framework/test-suites/bat-tests/__init__.robot
Robot-Framework/test-suites/bat-tests/apps.robot
Robot-Framework/test-suites/bat-tests/business_vm.robot
Robot-Framework/test-suites/bat-tests/gui-vm.robot
Robot-Framework/test-suites/bat-tests/timesync.robot

In addition
- Removed cursor movements implemented to prevent auto suspend
- Close the ssh connections which are not going to be used
- Include timesync test into lenovo-x1 tests

Fix bat init and disable suspend after login

---

Robot-Framework/resources/common_keywords.resource
Robot-Framework/test-suites/gui-tests/gui_apps.robot

At first launch chrome opens window for selecting account. At the moment this window is closed it opens still another window, the actual browser window. This is a feature of chrome and we need to adapt the launch test for that.
This PR handles also the situation that chrome has already been launched and only single window needs to be closed. 
Different scenarios can be tested by manually opening 0-2 chrome windows prior to running the test SP-T41.

Enable chrome launch test to close another window

---

Robot-Framework/test-suites/bat-tests/apps.robot
Robot-Framework/test-suites/bat-tests/business_vm.robot
Robot-Framework/test-suites/bat-tests/netvm.robot
Robot-Framework/test-suites/bat-tests/optee.robot
Robot-Framework/test-suites/bat-tests/others.robot

The idea is to select the most robust & reliable cases at first to start with.  More tests are going to be tagged one by one when a test is seen having such maturity that it should fail only if there is really something wrong
Selected tests:
Start Chrome on LenovoX1
Test ghaf version format
Test nixos version format
Check systemctl status
This PR changes only automated test tags, we need to finetune the 'pre-merge' jenkins pipelines a bit as well due to this.

Tag 'pre-merge' set only for selected 4 tests.

---

Robot-Framework/test-suites/bat-tests/apps.robot

Test temporarily disabled from mentioned targets.

Remove tags(nuc, orin-agx) from Start Firefox

---

Robot-Framework/resources/gui_keywords.resource

1. Add a reset for automatic scaling (https://github.com/tiiuae/ghaf/pull/960). Without reset tests are not able to confirm logged in state and almost all of them fail. Works also with current mainline version so can be merged in before #960.
2. Fix Stop swayidle. I noticed that it was not working anymore and it has probably been broken since user accounts were added.

Add scaling reset to GUI Log in

---

flake.nix
pkgs/ghaf-robot/default.nix
pkgs/robotframework-debuglibrary/default.nix
requirements

Configured the 'robotframework-debuglibrary' -package in to the system.
Usage: One can set a ' break point' into the robot framework code and stop the test into some interesting phase.
When test case stopped a debugging command shell opens and one can give robot framework keywords into that & see the results. This is usable feature when developing new tests/debugging the old ones.
This is not set on by default for all the files but one needs to set  2 lines described below if one want to use the feature.
Usage:
1) Add '**Library    DebugLibrary**' into the 'robot file' you want to set 'debug break point'
```
*** Settings ***
...
Library            DebugLibrary
```
2) Add '**Debug**' into the same 'robot-file' to line you want execution to stop
```
...
Do something
Log to console  Debug …
```

Add 'robotframework-debuglibrary' -package to QA test environment

---

Robot-Framework/lib/PerformanceDataProcessing.py

current view in correct order:

Keep order of performance results

---

Robot-Framework/resources/ssh_keywords.resource

The goal is to make the logs more clear. Now there are sometimes multiple `Connecting to gui-vm` logs after each other.
Example of the output:
```
Creating test user
Connecting to gui-vm as milla
Connecting to gui-vm as ghaf
Logged out state detected. Logging in.
Connecting to gui-vm as ghaf
Check: ydotool daemon running
Typing username and password to login
Connecting to gui-vm as ghaf
Typing
Pressing Enter
Connecting to gui-vm as ghaf
Typing
Pressing Enter
Trying to reset scaling
Connecting to gui-vm as milla
Auto scaling reset failed
```

Log user when connecting to vm

---

Robot-Framework/test-suites/bat-tests/netvm.robot

Remove 2 tests from Orin-AGX execution since there is still something to investigate.

Remove netvm restart tests from OrinAGX scope

---

Robot-Framework/config/variables.robot
Robot-Framework/resources/connection_keywords.resource
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/bat-tests/check_logs.robot
Robot-Framework/test-suites/bat-tests/netvm.robot

This is related to https://github.com/tiiuae/ghaf/pull/915 and should be merged at the same time.
Changes:
- Net-vm ip address changed from 192.168.101.1 to 192.168.100.1.
- Debug Ethernet connection is now connected to net-vm instead of host. Changed the tests to take connection to host through net-vm.
Known issues on X1:
- Netvm-tests have been commented out until they are reworked.
- Tests in others.robot fail or do not work correctly. They used to be run in host but after changes they are now run in net-vm. Should be moved back to host, but that was not straight forward.
- Some performance tests fail, did not yet check why. Probably connections are getting mixed.
Notes:
- I only tested locally on X1.
- This should also be validated in Jenkins pipeline and with Orins.

Update network connections

---

Robot-Framework/config/variables.robot
Robot-Framework/resources/connection_keywords.resource
Robot-Framework/resources/gui_keywords.resource
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/bat-tests/__init__.robot
Robot-Framework/test-suites/bat-tests/check_logs.robot
Robot-Framework/test-suites/bat-tests/netvm.robot

Continuing from https://github.com/tiiuae/ci-test-automation/pull/222 (which was later reverted by https://github.com/tiiuae/ci-test-automation/pull/227) to adapt ci-test-automation to new network settings:
X1: ethernet-USB adapter connects to net-vm, not anymore to ghaf-host
Orin-AGX: ethernet interface still on ghaf-host (same as before)
Orin-NX: ethernet-USB adapter interface still on ghaf-host and ethernet interface on net-vm (same as before)

Adapt to ghaf pr915

---

Robot-Framework/test-suites/performance-tests/network.robot

There was an extra layer of harcoded check for iperf tests in keyword Get Throughput Values in addition of applying the adaptative result analysis tooling of PerformanceDataProcessing. Pass/fail criteria of that extra check was based on single hard coded limit for all targets. 
However results show that different targets have different baselines. The existing general result analysis tooling is able to adapt to different baselines on different targets and can detect any significant deviation from baseline. Extra check is not needed.
Added some extra logging in case measurement result is empty.

Remove check against hard coded limits in iperf result analysis

---

Robot-Framework/test-suites/boot-test/relay_boot_test.robot

Previously only the old boot test was fixed but forgot to add the fix also to the new relay boot test.

Fix lenovo-x1 relay boot test

---

Robot-Framework/test-suites/bat-tests/timesync.robot

Timesync -test: Changed tolerance to be 30s instead of default one used in python -script (10s)

Change timesync tolerance to be 30s instead of 10s.

---

Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/bat-tests/others.robot

Added new keyword: 'Check Internal eMMC Size for reading internal memory.
The tests 'Check Memory status was changed in a way that if 'lsblk' lists something including 'sda' -> it is supposed that device is booted from SSD, otherwise from internal memory.
The actual size check was not touched so the criteria is same for both memory checks.

Add memory test also to address internal memory.

---

Robot-Framework/config/variables.robot
Robot-Framework/lib/send_report.py
Robot-Framework/resources/gui_keywords.resource
Robot-Framework/test-suites/bat-tests/__init__.robot
flake.nix

The purpose of this PR is to bring more flexibility into manual use of ci-test-automation and to make local smoke testing faster. Fully automated setups should not be affected.
CONFIG_PATH (path to test_config.json) can be given via command line. If not given it defaults to the current path. 
If CONFIG_PATH is set to `None` reading config file variables will be ignored which allows setting target IP address from command line. This makes local testing more straightforward, not having to create or modify test_config.json.
Prevents Set Variables from overwriting password (given via cmd line) if /run/secrets/dut-pass does not exist.
Custom test user name and password are now allowed. They can be stored to /etc/secrets/testuser and /etc/secrets/testpw. If those files don't exist test user …

Allow setting more variables via command line

---

Robot-Framework/test-suites/bat-tests/netvm.robot

The test needs to be re-worked for X1. Disabling it for now.

Disable wifi passthought test for lenovo-x1

---

Robot-Framework/resources/common_keywords.resource
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/resources/virtualization_keywords.resource
Robot-Framework/test-suites/bat-tests/netvm.robot
Robot-Framework/test-suites/bat-tests/optee.robot
Robot-Framework/test-suites/boot-test/boot_test.robot
Robot-Framework/test-suites/boot-test/relay_boot_test.robot
Robot-Framework/test-suites/gui-tests/__init__.robot
Robot-Framework/test-suites/gui-tests/gui_power_options.robot

After ethernet interface was passed through to net-vm on lenovo-x1 iterative check of login to net-vm was first added to boot tests of lenovo-x1. Failures after gui reboot tests showed that iterations have to be added to the Connect keyword instead of using them only in the boot test.
The default number of iterations in Connect is 1 (as previous) but in boot tests and gui reboot 10 iterations are given.
Also Orin-NX needs to have iterative Connect keyword at boot and the output target has to be net-vm as with lenovo-x1. Both lenovo-x1 and orin-nx expose ghaf-host for about 10 sec time window at boot. During that time window ssh login attempts end up to ghaf-host.
- Modified also `Connect to ghaf host` to connect via net-vm on Orin-NX (as with lenovo-x1).
- Removed orin-nx tag from those …

Add iterations to Connect keyword

---

Robot-Framework/resources/ssh_keywords.resource

It was noticed that the whole Connect keyword can fail if Login of single iteration fails. With this change it will be avoided. 
In the beginning of boot ethernet interface is on ghaf-host but gets then passed through to net-vm at some point. If the switch of ethernet interface from ghaf-host to net-vm happens between Open Connection and Login keywords it is possible that the opened connection is actually lost in between and thus Login fails. This can randomly fail the Login keyword of the iteration at boot.

Prevent fail in connect iteration to fail the keyword

---

Robot-Framework/test-suites/bat-tests/others.robot

It is a known issue that the status is degraded. Bug has been opened.

Remove systemctl status check from Orin-NX for now

---

Robot-Framework/test-suites/security-tests/ip_spoofing_test.robot

Fixes connections that were not working correctly after network changes. Also simplifies the test a bit by removing unnecessary steps.
[Test run report](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/508/artifact/Robot-Framework/test-suites/lenovo-X1ANDipspoofing/report.html#tags?lenovo-x1)

Fix IP spoofing

---

Robot-Framework/test-suites/gui-tests/__init__.robot
Robot-Framework/test-suites/gui-tests/gui_apps.robot

Added some more tests starting applications from GUI. (Calculator, BT, Control Panel & File Manager)
Also added 'test user creation' to GUI test setup in case the suite is executed as 'standalone'.
Test passed in Jenkins pipeline: [502](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/502/console) (Jenkins failed to assign results to the build, but that has nothing to do with tests)

Add some more GUI tests.

---

Robot-Framework/resources/ssh_keywords.resource

There has been a lot of situations where test run gets stuck forever at SSHLibrary.Login keyword. This keyword doesn't have native timeout argument but let's create own `Login with timeout` keyword which has. 
If timeout happens iterations of Connect keyword won't still be run. Iterations are useful only in case target hostname check fails.
In addition:
- Add check for the target hostname in Connect to VM.
- Set NETVM_SSH index in Connect keyword for Lenovo-X1 and Orin-NX targets. This will ensure that further use of Connect to VM will always have correct jumphost index available. It should fix problems in GUI reboot test on Lenovo-X1.

Create and apply own Login keyword with timeout

---

Robot-Framework/test-suites/bat-tests/netvm.robot

Because net-vm has internet connection already via ethernet WiFi connection cannot be verified by checking the internet connection. Presence and absence of WiFi connection is verified by checking if an IP address has been assigned to WiFi interface.
Tested in dev jenkins and it passed:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/521/artifact/Robot-Framework/test-suites/lenovo-x1ANDSP-T101/report.html#totals

Modify WiFi test for Lenovo-X1

---

Robot-Framework/resources/ssh_keywords.resource

This change reduces the Lenovo-X1 bat suite length by 4.5 minutes from 12.5 minutes to 8 minutes - a decrease of about 35 %.
It seems that every time one of the processes is killed, all the others are also terminated simultaneously. This change adds a check after process is killed to see if any of the processes are still running. If none are running, there is no need to go through & kill them one by one. 
Killing processes one by one takes a long time. For Chrome it took about 74 s. With this change it now only takes 5 s.
[Nightly pipeline](https://ghaf-jenkins-controller-prod.northeurope.cloudapp.azure.com/job/ghaf-hw-test/2346/robot/report/bat/report.html) (12:36)
[Test run with Lenovo-X1](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/547 …

Optimize Kill process

---

Robot-Framework/test-suites/bat-tests/__init__.robot

There has been some Jenkins pipeline freezing lately with Orin-NX. Last one this morning had to be aborted manually and it was noticed that actually tests got passed but the teardown did freeze for some unknown reason.
In order to avoid pipeline stucks due to possible test case execution failures, a 10 min timeout was set for bat tests. 
For the bat-test 'setup & teardown', a 5 min timeout was set.
In addition to this, we should ask devops persons about the possibility to add timeout also for Jenkins jobs.
We really cannot be sure about the root causes: Sometimes it maybe that tests/testHW freezes(fails) , sometimes there might be something Jenkins related issues ongoing.
Test results: Orin-NX[584](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-t …

Add timeouts for bat test execution.

---

Robot-Framework/test-suites/performance-tests/network.robot

Changes to get these 8 tests to work on Lenovo-X1 & Orin-NX as well. Needed to work with firewall settings. Other Devices than Lenovo-X1 or Orin-NX will use the original solution  (iptables -F still left as was for the other targets) 
Changes:
- Selection where to connect, if Lenovo or NX -> net-vm, other targets ghaf-host
- Opened port 5201 from iptables. Originally this was issue since using flushing (iptables -F ) in 'net-vm' got the net-vm into 'totally stucked -state.'
- Moved starting/stopping of 'iperf server' to Suite SetUp/Suite Teardown ( started/stopped only once -> more robust, and bit faster execution) compared to the original solution where iperf-server was started/stopped in every test separately.
- In local trials there was some random test failures-> added a keyword to …

Update performance tests.

---

Robot-Framework/test-suites/performance-tests/network.robot

There perf tests are failing on 'Orin-NX' when executed via Jenkins. Same code works fine locally. 
Taking tests out from mentioned target out until root cause is identified & fixed

Remove 'orin-nx' tags from perf/network -suite.

---

Robot-Framework/test-suites/performance-tests/performance.robot

FileIO test has bee failing for a while on NUC. 
Removing tag until there is some implementation changes done to enable fixing.
Test result on prod HW: [x-gahf-test 80](https://ghaf-jenkins-controller-prod.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/80/)

Remove 'nuc' -tag from 'FileIO test'.

---

Robot-Framework/resources/ssh_keywords.resource

When investigating issues with Orin-AGX's netvm tests, it was noticed that 2 keywords are not working as expected.
**Connect to VM**
- '_Opening connection_' and '_Login with timeout_' were inside FOR LOOP under same TRY.  If _'Login with timeout'_ failed, the LOOP did not execute the next round but ended up there. The code was changed in such way that 1st the connection is opened in own for -loop and after that there is own for -loop for logging in.
Original problem is visible here: [181](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test-mikkos/181/robot/report/log.html)
**Verify service status**
The result of checking if log contain 'Welcome to NixOS'  was never used for real. If expected status/state was 'inactive/dead' and those got values …

Refactor 2 keywords.

---

Robot-Framework/test-suites/bat-tests/gui-vm.robot

Noticed that `Start Bluetooth Settings on LenovoX1` always passes. Fixed it by changing the search to use unique name.
`Check that the application was started` runs `grep` with argument. Issue was that even before Bluetooth Settings is opened there is two processes running with `blueman` in the name. Because of that it did not matter if the app opened or not, running process was always found.
```
[milla@gui-vm:~]$ ps aux | grep blueman | grep -v grep
milla       1300  1.6  0.4 628140 59084 ?        Sl   07:58   0:00 /nix/store/0l539chjmcq5kdd43j6dgdjky4sjl7hl-python3-3.12.8/bin/python /nix/store/2jriiij72vpc3kz59kvn02q8gj7kybdv-blueman-2.4.4/bin/..blueman-applet-wrapped-wrapped
milla       1494  0.6  0.2 443360 28520 ?        Sl   07:58   0:00 …
```

Fix Start Bluetooth Settings

---

Robot-Framework/resources/ssh_keywords.resource

Excluding 'Welcome to NixOS' waiting from Lenovo & Dell, it is enough to check if process status and state are as expected.
Tests on Orin-AGX: [782](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/782/robot/report/log.html)

Exclude welcome check for Lenovo & Dell.

---

Robot-Framework/config/variables.robot
Robot-Framework/test-suites/performance-tests/performance.robot

In case of using non-default output directory the path to performance plots was set absolute. If report.html is opened from the location it was originally created it can show the links to performance plots but if the result folder is moved to another location the links to plots are broken in report.html.
This commit sets relative path to performance plots also for non-default output directory as it is the case for default output directory.

Change plot_dir to relative path

---

Robot-Framework/test-suites/bat-tests/netvm.robot

On Orin-AGX netvm tests 
- NetVM is wiped after restarting & 
- Verify NetVM PCI device passthrough fails randomly.
Suspected reason is that the device gets into 'Unrecoverable error detected' -state.
If the mentioned tests (for mentioned HW fail), the skip is set with the bug's ticket ID.
Test result (no failures): [851](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/851/)
Test result (with failures): [853](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/853/)

Add skip for 2 known failures.

---

Robot-Framework/resources/common_keywords.resource

There has been cases where Bat -test suite's Teardown stucks on Orin-NX when trying to capture the content of 'journal.txt' into a variable. The Issue happens randomly so it is hard to capture intentionally. Currently there is 5 min timeout that triggers the tesrdown to fail.
This failure causes the situation where all the executed tests are marked as failed even if that is not true.
The implementation was changed in such way that the 'cat' command is not used but the 'jrnl.txt' file is copied and saved 
-> the hiccups with 'cat' should be avoided now and saving the file should be more robust way to handle this.
Some more testing with DEV setup where 'Ghaf HW test' got script from this branch.
Testing (together with jenkins groovy changes …

Save jrnl.txt instead 'cat jrnl.txt'.

---

Robot-Framework/lib/ParseMemoryLogData.py
Robot-Framework/lib/ParsePowerData.py
Robot-Framework/resources/power_meas_keywords.resource
Robot-Framework/test-suites/boot-test/relay_boot_test.robot
Robot-Framework/test-suites/performance-tests/ballooning.robot
Robot-Framework/test-suites/performance-tests/boot_time_test.robot
Robot-Framework/test-suites/performance-tests/consume_memory
Robot-Framework/test-suites/performance-tests/log_memory
Robot-Framework/test-suites/security-tests/__init__.robot
Robot-Framework/test-suites/security-tests/ip_spoofing_test.robot
Robot-Framework/test-suites/security-tests/nc_client
Robot-Framework/test-suites/security-tests/nc_server
Robot-Framework/test-suites/security-tests/nc_stealer

Ballooning monitor should allocate more memory for a VM when its available memory approaches 0. 
This test case is first consuming and then releasing a lot of memory while simultaneously logging total, used and available available memory of the VM. Test keyword is generic, can be used for any VM but suitable parameters have to be checked if applying to other VMs than those now applied.
All VMs don't have memory ballooning enabled. Other VMs can have different maximum limit for inflating total memory.
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/979/
***
Checked that currently on ghaf side the default limit for memory ballooning has been set to 2 x vm initial memory:
(modules/microvm/appvm.nix)
```
balloonRatio = mkOption {
description = …
```

Measure dynamic increase and decrease of memory

---

drcontrol/drcontrol.nix
drcontrol/flake.nix
flake.nix

NixOS/nixpkgs#394838
This forces the correct inclusion of the packages that a derivation needs without relying on the namespace inclusion. Ultimately fixes override and improves cross-compilation.

fix: breaking change in python3Packages handling

---

Robot-Framework/test-suites/bat-tests/gui-vm.robot
Robot-Framework/test-suites/gui-tests/gui_apps.robot

Should be merged before https://github.com/tiiuae/ghaf/pull/1154
Falcon AI app does not open directly from the icon anymore. Instead it starts downloading the Falcon3 model and only opens after the download has finished. Testing this should be added as a separate test case.

Remove Falcon AI test cases

---

Robot-Framework/lib/PerformanceDataProcessing.py
Robot-Framework/lib/performance_thresholds.py
Robot-Framework/resources/performance_keywords.resource
Robot-Framework/test-suites/performance-tests/boot_time_test.robot
Robot-Framework/test-suites/performance-tests/network.robot
Robot-Framework/test-suites/performance-tests/performance.robot

Modified the performance result analysis and baseline tuning so that it switches to new baselines only after defined number of deviations in a row (to the same direction: increase/decrease). The threshold for number of successive deviations is defined as `'wait_until_reset'` in `Robot-Framework/lib/performance_thresholds.py`. Any opinions if 5 is good number are welcome.
Also did major reformations for `Robot-Framework/lib/PerformanceDataProcessing.py` and `Robot-Framework/test-suites/performance-tests/performance.robot`, and touched few other files too.
- Created `calculate_statistics` function which handles statistics calculations for every test case (except for `Sysbench test in VMs on LenovoX1`). For now every test case have had those things done in their `read_***_csv_and_plot` …

Refactor performance result analysis

---

Robot-Framework/resources/power_meas_keywords.resource
Robot-Framework/test-suites/suspension-test/suspension.robot

Global variable SSH_MEASUREMENT was not reset to EMPTY after 'GUI Suspend and wake up' test although its
Teardown runs Close All Connections. When power measurement was implemented to another test case it switched to a non-existent ssh connection at 'Connect to measurement agent', SSH_MEASUREMENT index being left over from the previous power measurement.
Prevent this by forcing SSH_MEASUREMENT to EMPTY in the beginning of 'Start power measurement' and not using Switch Connection at all for power measurement agent. Then the power measurement tooling will allow continuous measurements even over multiple test cases if required.
Also moved 'Start power measurement' to the beginning of 'Automatic suspension' test and added
'Set start timestamp' which is necessary for getting start time when …

Fix power measurements

---

Robot-Framework/test-suites/bat-tests/internet.robot

Simple test that pings google from every vm to confirm that internet connection passthrough works.
Testruns:
[Lenovo-X1 normal mainline](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1164/) (passthrough works)
[Dell-7330 normal mainline](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1168/) (passthrough works)
[Lenovo-X1 mainline extras image](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1165/) (passthrough does not work)

Add test for VM internet connection

---

Robot-Framework/lib/ParseMemoryLogData.py
Robot-Framework/lib/PerformanceDataProcessing.py
Robot-Framework/resources/performance_keywords.resource
Robot-Framework/test-suites/performance-tests/boot_time_test.robot

For now measure only time to ping response on Orins. Measuring time to desktop would require display connected.
Added 'inverted' argument to Determine Test Status for test cases where decrease in test result value would mean improvement and vice versa.
Test runs
orin-nx:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1194/
lenovo-x1:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1198/

Add boot time measurement for Orins

---

Robot-Framework/test-suites/suspension-test/suspension.robot

Reconnecting device in case of power measurement usage in PROD.
The test worked fine in DEV since the RPI connection is not  used there.
Test result(PROD): https://ghaf-jenkins-controller-prod.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/180/ 
Test result (DEV): https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1224/

Re-establish 'normal' connection after connecting to RPI in PROD

---

Robot-Framework/test-suites/suspension-test/suspension.robot

The timeout used to launch the power measurement script on the measurement agent was only 180 sec but according to the test report logs the Automatic suspension test lasts around 20 min 30 sec. Increase the timeout well beyond the duration of the test case, to 1500 sec.
Then we will see power plot over the full automated suspension and wake up, not just 3 min from the beginning when suspension hasn't yet kicked in.

Give enough time for the power measurement script

---

Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/performance-tests/boot_time_test.robot

Orin-NX performance tests had failed to execute, the setup keyword had failed.
When checking this, it was noticed that connection to 'net-vm' was not established but connected tartget was still 'ghaf@ghaf-host'
There was just one  'open connection'  trial set as default for loop, that was increased to be '3' and now the connection seem to take place.
Failed run: [perf-5930](https://ghaf-jenkins-controller-prod.northeurope.cloudapp.azure.com/job/ghaf-hw-test/5930/artifact/Robot-Framework/test-suites/performance/log.html)
With fixes [dev-1231](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1231/robot/report/log.html)

Fix Orin-NX connection issues.

---

Robot-Framework/config/variables.robot
Robot-Framework/resources/common_keywords.resource
Robot-Framework/resources/gui_keywords.resource
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/bat-tests/__init__.robot
Robot-Framework/test-suites/bat-tests/business_vm.robot
Robot-Framework/test-suites/bat-tests/gui-vm.robot
Robot-Framework/test-suites/gui-tests/__init__.robot
Robot-Framework/test-suites/gui-tests/gui_apps.robot
Robot-Framework/test-suites/gui-tests/gui_power_options.robot
Robot-Framework/test-suites/security-tests/ip_spoofing_test.robot
Robot-Framework/test-suites/suspension-test/suspension.robot

Add support for running Lenovo-x1 tests on Cosmic. There should be no major changes when Labwc is in use. Compositor is detected automatically. 
* Use `Tab and enter` to navigate app menu & power menu instead of image recognition and clicking. Those menus don't recognize teleported mouse and clicking does not work.
* I tried using wlrctl tool instead of ydotool, but Cosmic does not yet support zwlr_virtual_pointer_manager_v1.
* New keywords `Log in, unlock and verify` and `Log out and verify` that take care of the whole login/logout operation.
* `Log out via GUI` uses Super+Shift+Escape keyboard shortcut to log out.  It should be more robust than opening power menu and clicking from there. Power menu log out is tested in GUI tests. 
* `Verify logout` renamed to `Check if logged out`. It …

Support Cosmic

---

Robot-Framework/resources/gui_keywords.resource

Sometimes on Labwc `Wait for Ghaf session activation `  fails because Ghaf session takes over a minute to start. There is no need to wait for it, `Verify desktop availability` will confirm if login worked or not.
`Wait for Ghaf session activation` was added because with Cosmic taking a screenshot before desktop is available causes issues. On Cosmic Ghaf session does not have the same dependencies so it starts faster and more reliably. Just like with Labwc, `Verify desktop availability` will confirm if login worked or not.
Example of a fail in [prod main pipeline ](https://ghaf-jenkins-controller-prod.northeurope.cloudapp.azure.com/job/ghaf-hw-test/5969/).
I did not manage to reproduce the issue in dev setup in a few tries. On my desk it did happen and I was able to verify that this works …

Do not fail if Ghaf session is inactive

---

Robot-Framework/resources/gui_keywords.resource
Robot-Framework/test-suites/bat-tests/gui-vm.robot
Robot-Framework/test-suites/suspension-test/suspension.robot

**List of changes**
1. `[Teardown] Connect to VM ${GUI_VM}` added for all keywords that login to testuser in gui_keywords.resources. For most of them it already is there. Makes it a lot easier to keep track where the connection is. (This cased the suspension test to fail - it was accidentally connected to testuser and not to ghaf after login)
2. Skip `Start Sticky Notes on LenovoX1` on Cosmic, the app is not available. Skip already exists for the GUI version but this was forgotten.
3. Increase `Check screen brightness` timeout 10s -> 60s. Sometimes dimming the screen just takes longer with Labwc. We could not find out why that is with Kajus. Since there is no strict requirement about the suspend times this solution will do for now. With Cosmic it is hopefully more reliable.
**Test runs** …

Small fixes after Cosmic change

---

Robot-Framework/lib/PerformanceDataProcessing.py
Robot-Framework/lib/performance_thresholds.py

Allow both absolute (int/float) and relative (string including value and '%' character) thresholds.
Set relative 40% threshold for iperf tests.
Add some clarifying doc lines to performance_thresholds.py.
Test run of x1 performance suite
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1267/

Enable usage of relative threshold values

---

Robot-Framework/resources/gui_keywords.resource

Dev -Dell HW seems no to be as fast as the one used in Prod.
Added delays in order to get the login Gui visible on screen.
Test Result: [1301](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1301/)

Add delays to wait login screen (Dell).

---

Robot-Framework/test-suites/gui-tests/gui_power_options.robot

For some reason the X1 in dev setup does not suspend or reboot as it should when using Cosmic. This is blocking adding the X1 Cosmic tests to nightly pipeline so let's just skip them for now. Once the image is built in the pipeline we can also test it in prod.
[Cosmic test run](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1302/)

Add skip to cosmic power tests

---

Robot-Framework/test-suites/bat-tests/timesync.robot

Orin-AGX HW in test setups is connected directly to network cable -> ghaf is having connection, netvm is not.
In order to get 'time synchronization from net' to work netvm should also have connection to net. 
In test case the Wifi connection is enabled for netvm to get synch done. Another way would be include network adapters to all test setups, but there might be some mac address etc issues around. 
Added also check that the syncronization info gets verified after the check loop.   
Test result: [dev #1312](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1312/)

Set Wi-Fi on for AGX in timesync -test.

---

Robot-Framework/test-suites/bat-tests/timesync.robot

Sometimes it requires more than currently set 3 sec. Let's set it to 20 sec.
Example of failing to get the time synchronized in 3 sec after switching timesync service on:
https://ghaf-jenkins-controller-prod.northeurope.cloudapp.azure.com/job/ghaf-hw-test/6186/artifact/Robot-Framework/test-suites/bat/log.html#s1-s1-s10-t1

Give more time for timesync

---

Robot-Framework/test-suites/bat-tests/gui-vm.robot
Robot-Framework/test-suites/gui-tests/gui_apps.robot

https://github.com/tiiuae/ghaf/pull/1158 bumped Sticky Notes to a version that does not currently open in Ghaf with Labwc.
Let's skip the Sticky Notes test cases until the fix is ready.
[Testrun](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1402/)

Add skip for Labwc Sticky Notes test cases

---

Robot-Framework/config/variables.robot
Robot-Framework/lib/PerformanceDataProcessing.py
Robot-Framework/lib/performance_thresholds.py
Robot-Framework/resources/performance_keywords.resource
Robot-Framework/test-suites/performance-tests/boot_time_test.robot
Robot-Framework/test-suites/performance-tests/network.robot
Robot-Framework/test-suites/performance-tests/performance.robot

Allow defining threshold as multiple of standard deviation. For now set only fileio threshold as multiple of standard deviations.
Fail the test always in case of zero result and omit zeros in statistics calculations. 
Label zero results with flag: -100
Test runs:
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1475/
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1493/

Add std threshold and handle zero results

---

Robot-Framework/test-suites/bat-tests/gui-vm.robot
Robot-Framework/test-suites/gui-tests/gui_apps.robot

Issue was fixed yesterday https://github.com/tiiuae/ghaf/pull/1206
[Testrun](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1505/)

Remove skip from Sticky Notes test cases

---

Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/bat-tests/netvm.robot

`Check if ssh is ready on vm` keyword gets sometimes stuck on `nc -zvw3 ${vm} 22` and the execution times out instead of trying again like it should. This has often happened to me locally and I have been using the timeout for already some time. Now for the first time I am also seeing it [in the lab](https://ghaf-jenkins-controller-prod.northeurope.cloudapp.azure.com/job/ghaf-hw-test/6853/robot/report/pre-merge/log.html#s1-s1-s1-t1
).
I also removed the `Check if ssh is ready on netvm` keyword and changed the two occasions that used it to use `Check if ssh is ready on vm`. These keywords were basically identical, I see no reason to have separate one for netvm (there might be some historical reason on why it ended up like this :)).

Improvement to Check if ssh is ready

---

Robot-Framework/test-suites/performance-tests/ballooning.robot

ballooning.robot missed PERF_LOW_LIMIT argument in library call. It was just recently added to PerformanceDataProcessing.py. Forgetting the argument in library call caused import of the whole library to fail and its keywords were not available.

Add missing argument for library call

---

Robot-Framework/resources/ssh_keywords.resource

Due to repeating problems in nc getting stuck let's try this additional timeout. 
Tested manually that if the command hit's this timeout the return code is 124.
nc command has got stuck especially when robot is already connected to gui-vm as ghaf and then before connecting to gui-vm as testuser robot tries to check if the ssh is ready on gui-vm. Well, of course it is ready if robot has already an established ssh connection to gui-vm. Added check if robot is already connected to the vm and if so ignore the keyword.
gui tests run on X1
https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1622/

Try additional nc timeout

---

Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/functional-tests/host.robot
Robot-Framework/test-suites/functional-tests/vm.robot
list_of_skipped_tests.md

Changes
1. Only skip the ghaf-host systemctl check (`Check systemctl status`) if the failed process is one of the known ones. **Note:** This _will_ cause failures that have previously been skipped. We should create bugs for the regularly failing services and then add  a skip with that ticket number.
2. New test case systemctl status on every VM for Lenovo-X1 and Dell-7330 (
`Check systemctl status in every VM`). **Note**: This test will always be skipped if it fails. Multiple services are currently failing across multiple VMs. Let’s collect some data for now and create bugs later.
3. Removed the unused `${close_conn}` argument from `Verify Systemctl status`
[Lenovo-X1 test run](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1661/) …

Refactor systemctl check

---

Robot-Framework/test-suites/performance-tests/boot_time_test.robot

When this separate Get Time To Ping keyword was created it was forgotten to invert the check for test status 
-> decrease is improvement and increase degradation.

Invert test status check for time to ping

---

Robot-Framework/test-suites/performance-tests/ballooning.robot

Ballooning suite/test did stuck in pipeline: https://ghaf-jenkins-controller-prod.northeurope.cloudapp.azure.com/job/ghaf-hw-test/7178/console.
To avoid that situation:
- Added test timeout of 5 mins (normally test takes ~2 minutes) 
- Changed 'Test Teardown' in such way that in case of timeout, the device will be Rebooted and the rest of the tests should be able to execute in pipeline after that.
This has not yet been tested in Jenkins pipeline, but locally it seems like this worked ok. 
Jenkins both passing: [Dev#1684](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1684/)
Jenkins where made timeout to happen: [Dev#1681](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1681/)

Add timeout for ballooning tests.

---

Robot-Framework/lib/output_parser.py
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/functional-tests/host.robot

Separated `Check systemctl status for known issues` to its own keyword, this keyword can also be used for the VM checks and gui-vm user check. Improved error handling in situations where multiple services have failed. Fixed one issue number.
[Orin-AGX](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1697/) testrun => skipped
[Lenovo-X1](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1698/) testrun => passed
[Dell-7330](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1700/) testrun => passed
[Dell-7330](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1705/) testrun => failed (used different …

Improve systemctl known issues check

---

Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/functional-tests/gui-vm.robot
Robot-Framework/test-suites/functional-tests/host.robot

`IF   $user` was always evaluated as true.
[Orin-AGX](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1723/)
[Lenovo-X1](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1724)

Fix Verify Systemctl status

---

Robot-Framework/test-suites/gui-tests/__init__.robot

There's a bug that occasionally causes the app menu to freeze on Cosmic, especially on the first login. Logging out once before running GUI tests helps reduce the chances of it happening.
[Run without this PR](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1725/)
[Run with this PR](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1728/)

Logout before GUI tests on Cosmic

---

Robot-Framework/test-suites/performance-tests/network.robot
list_of_skipped_tests.md

AGX is failing the Measure UDP Bidir Throughput Big Packets -test (gets Flat RX in iperf test)
There is an open ticket SSRCSP-6623: Bidirectional iperf test results drop on Orin with 6.6 kernel
Set 'Skip' for test failure until the problem gets solved.
Test Result: [Dev#1746](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/1746/)

Skip for known issue (Measure UDP Bidir Throughput Big Packets(AGX))

---

Robot-Framework/test-suites/functional-tests/gui-vm.robot

There was already a dedicated keyword for checking if failure is known and it takes account also if there are more failures than only one.  Replaced SKIP -inspection with that.
TestResult: [DEV#252(https://ghaf-jenkins-controller-prod.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/252/)

Refactor failure/skip inspection.

---

Robot-Framework/test-suites/functional-tests/logging.robot

Logging variables were changed in https://github.com/tiiuae/ghaf/pull/1250
[Testrun](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2169/)

Fix logging query

---

Robot-Framework/resources/ssh_keywords.resource

Ballooning test started to fail frequently. Investigated this and noticed that 30s timeout for 'Check if ssh is ready on vm' was no more  enough. Took the default timeout(60) set on actual keyword 'connect to vm' into use. 
Tests:
Without the fix: [Dev#2264](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2264/artifact/Robot-Framework/test-suites/lenovo-x1ANDSP-T255/log.html)
With the fix: [Dev#2263](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2263/artifact/Robot-Framework/test-suites/lenovo-x1ANDSP-T255/log.html)

Fix for Ballooning test  (Set timeout for a keyword)

---

Robot-Framework/resources/common_keywords.resource
Robot-Framework/resources/gui_keywords.resource

[Normal test run](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2280)
[No launcher icon, power icon found](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2276/)
[No launcher icon or power icon ](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2279/)
I manually blocked the icons to test. Artifacts are not saved for ghaf-hw-tests so the log file does not exist in Jenkins. Tested it locally.

Search for power icon, save journalctl log if launcher icon was not found

---

Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/functional-tests/apps.robot

After writing to `/tmp/out.log` file as ghaf user in `Open PDF from gui-vm` testuser cannot anymore write to that file because it was created by ghaf with related permissions.
So test cases `Open image with Oculante` and `Open text file with Cosmic Text Editor`
failed if `Open PDF from gui-vm` was run first.
Fixing this by removing `/tmp/out.log` file in the
Teardown of `Open PDF from gui-vm`.
This is something to be aware of in the future also since many tests leave out.log / output.log files hanging around in multiple vms of ghaf. However, the problem activated only in gui-vm since we don't use multiple users in other vms. Also test cases in gui-apps.robot could have failed but the thing that saved them is that they write stdout to different file (by `Start XDG application`): …

Fix Open Image and Open text file

---

Robot-Framework/config/variables.robot
Robot-Framework/test-suites/functional-tests/docker-vm.robot
Robot-Framework/test-suites/functional-tests/gui-vm.robot
Robot-Framework/test-suites/functional-tests/host.robot
Robot-Framework/test-suites/functional-tests/netvm.robot
Robot-Framework/test-suites/functional-tests/timesync.robot
Robot-Framework/test-suites/functional-tests/vm.robot

- Add support for running tests on FMO targets with the tag `fmo`
- Modify VM tests so that they first get the list of VMs that are running in the system and then run the tests for those VMs.
[Testrun on FMO Lenovo-X1](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2361/)
[Testrun on normal Lenovo-X1](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/tests/job/x-ghaf-hw-test/2365/) with fmoANDlenovo-x1 tag

Add support for FMO target

---

Robot-Framework/lib/helper_functions.py
Robot-Framework/resources/common_keywords.resource
Robot-Framework/resources/gui_keywords.resource
Robot-Framework/resources/power_meas_keywords.resource
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/functional-tests/gui-vm.robot
Robot-Framework/test-suites/gui-tests/gui_apps.robot
Robot-Framework/test-suites/gui-tests/gui_power_options.robot
Robot-Framework/test-suites/gui-tests/input_control.robot

Create general keyword which can be used in switching to any vm like Switch to gui-vm as ghaf/user.
Replace Switch to gui-vm as ghaf/user keywords with
`Switch to vm    gui-vm`
and 
`Switch to vm    gui-vm  user=${USER_LOGIN}`
**NOTES:** 
After using `Close All Connections` keyword previously automatically created connection index variables still exist and have some value but the connections related to the indices are lost. So even though `Check variable availability` passes it doesn't ensure that the connection is still active. `Try to switch to active gui-vm connection` is still very important in handling the situations after `Close All Connections`.
I read from Robot Framework documentation that `Switch Connection` actually returns the index of the previous connection not index of the …

Generalize keyword for switch to vm

---

Robot-Framework/resources/gui_keywords.resource

Boot order was changed a few weeks ago in https://github.com/tiiuae/ghaf/pull/1169. After that `ghaf-session.target` has not anymore worked properly for detecting when login has finished. This is most likely the reason for the execution getting stuck when trying to take a screenshot (for example [here](https://ci-prod.vedenemo.dev/job/ghaf-hw-test/222/) and [here](https://ci-prod.vedenemo.dev/job/ghaf-hw-test/140/)).
**Changes**
- Replace `ghaf-session.target` with  `xdg-desktop-portal.service` in `Wait for Ghaf session activation` (now called `Wait for user session to be active`)
- Require the `xdg-desktop-portal.service` to be active before continuing to launcher check. With Labwc the ghaf-session just sometimes did not active so we did not fail the test because of it. That issue should …

Fix login verification

---

Robot-Framework/resources/common_keywords.resource
Robot-Framework/resources/gui_keywords.resource
Robot-Framework/test-suites/functional-tests/gui-vm.robot
Robot-Framework/test-suites/suspension-test/__init__.robot
Robot-Framework/test-suites/suspension-test/suspension.robot

**Changes**
- Adapt suspension test case to https://github.com/tiiuae/ghaf/pull/1270 (The screen now turns off again after 7.5 minutes, brightness might not be at 100% after boot/login).
- Start to use `switch to vm` in suspension tests.
- Remove the reboot from the suspension test setup. With Cosmic there should be no need to reboot.
- Remove some dead code related to Mako.
**Testrun**
- [Lenovo-X1](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/35/) suspension & falcon

Update suspension test

---

Robot-Framework/resources/device_control.resource
Robot-Framework/test-suites/boot-test/boot_test.robot
Robot-Framework/test-suites/boot-test/relay_boot_test.robot
Robot-Framework/test-suites/performance-tests/ballooning.robot
Robot-Framework/test-suites/performance-tests/performance.robot

Replace word "Lenovo-X1" with "laptop" in those cases where it should apply both to lenovo-x1 and dell targets.
Remove one unused keyword.
Test runs on Dell
https://ci-dev.vedenemo.dev/job/ghaf-hw-test/131/
https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/134/

Use more general term "laptop" instead of "Lenovo-X1"

---

Robot-Framework/resources/gui_keywords.resource

`.log` file was not getting copied correctly from the test agent.
Tested in dev by changing
`${APP_MENU_LAUNCHER}   ./launcher.png` -> `${APP_MENU_LAUNCHER}   ./search.png`
in gui_keywords.resource
https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/196/

Change gui-vm log to be a txt file

---

Robot-Framework/test-suites/performance-tests/ballooning.robot
Robot-Framework/test-suites/performance-tests/consume_memory
Robot-Framework/test-suites/performance-tests/log_memory

This PR makes ballooning test tooling more general and suitable also for Dell target.
Use expected_inflate_ratio instead of hard coded size for expected inflated memory. This way the keyword should work for any vm regardless of the configured initial memory. In ghaf configuration default ballooning ratio is 2, so let's set expected_inflate_ratio a bit lower.
Noticed that shortly after ssh login total memory of the vm can be very high (17Gi) and mem-manager service slowly decreases it. So need to give it enough time to reduce the memory. Ballooning test should start from deflated state, not when the memory of the vm is still inflated. This is especially for the slow dell target but also lenovo-x1 has sometimes vms still in inflated state after connecting to them. Added a loop for initial …

Add Dell-7330 to ballooning test

---

Robot-Framework/lib/PerformanceDataProcessing.py
Robot-Framework/resources/serial_keywords.resource

Save journalctl.txt instead of journalctl.log in `serial_keyword.Save log` (for jenkins controller to be able to save it).
**Testrun with modified branch forcing relayboot to fail ssh connection test and `Verify init.scope status via serial`**
https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/268/
If a performance test has not yet valid measurement results in its measurement history (all results are below self.low_limit) let's just plot a single marginal self.low_limit, not some marginal calculated from the invalid measured values. (upper_marginal should actually be N/A before baseline but as we are plotting the marginals without legend we can just plot the same marginal twice.)
**Demonstrated with an iperf test case producing constantly invalid results:** …

Small fixes

---

Robot-Framework/test-suites/functional-tests/__init__.robot
Robot-Framework/test-suites/gui-tests/__init__.robot
Robot-Framework/test-suites/suspension-test/__init__.robot
Robot-Framework/test-suites/suspension-test/suspension.robot

suspension test failed after 5 minutes timeout exceeded in its teardown: https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/267/artifact/Robot-Framework/test-suites/suspensionANDlenovo-x1/log.html

Fix keyword timeouts

---

Robot-Framework/lib/PerformanceDataProcessing.py

Make it more clear which data points are considered deviation or invalid by the test automation.
Changes only visualization of the data.
**Demo runs:**
https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/358/
https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/362/
(open the plots to see the effect)
A local demo run

Highlight deviated values in performance plots

---

Robot-Framework/resources/common_keywords.resource
Robot-Framework/resources/gui_keywords.resource
Robot-Framework/resources/performance_keywords.resource
Robot-Framework/resources/serial_keywords.resource
Robot-Framework/resources/setup_keywords.resource
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/__init__.robot
Robot-Framework/test-suites/functional-tests/gui-vm.robot
Robot-Framework/test-suites/performance-tests/network.robot
Robot-Framework/test-suites/performance-tests/performance.robot
Robot-Framework/test-suites/security-tests/__init__.robot
Robot-Framework/test-suites/suspension-test/__init__.robot
Robot-Framework/test-suites/suspension-test/suspension.robot

Changes:
1. Now there is common __init__ file for ALL test suites, where "global" setup is defined. Here we initialize variables. This will require to use these variable in all other test suiltes' init files, especially use device control library.
2. Suspension test: after waking up od the device - check that lock screen appeared. In case is test fails, reboot laptop.
3. Replace "Log To Console" with "Log" + console=True for comments with variables, to be able to see them in reports, not only in logs.
Example of the failed suspension test with reboot in the test teardown: https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/408/artifact/Robot-Framework/test-suites/SP-T162/log.html
Here are 3 levels of setups/teardowns:

Refactor setups and teardowns

---

Robot-Framework/test-suites/functional-tests/audio.robot

- This PR does not significantly change how the test works, only makes them faster. Audio tests take about half the time they used to after this PR.
- Separated `Record Audio And Verify` into separate test cases so that only some of them can be included into pre-merge if necessary.
- Added comms-vm to audio tests. It should probably have been added right after it was created but better late than never.
[Lenovo-X1](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/469/)
[Dell-7330](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/472/)

Optimize audio test

---

Robot-Framework/resources/gui_keywords.resource

Robot [timeout] in `GUI Tests Setup` keyword (gui-tests/__init__.robot) might not always be passed down in the hierarchy of nested keywords. Again we saw test automation getting stuck at screenshotting:
https://ci-prod.vedenemo.dev/job/ghaf-hw-test/1993/console
```
00:26:28  Logging in
00:26:39  Typing password
00:26:43  Pressing key(s): ENTER
00:26:47  Switched to gui-vm as testuser
00:26:53  Waiting for the user session to be active...0.1.2.3.4.5.6.7.Success
00:26:53  User session is active, user is logged in
00:26:53  Switched to gui-vm as ghaf
00:26:53  Verifying login by trying to detect the launcher icon
00:26:53  Switched to gui-vm as testuser
00:26:53  Taking cosmic screenshot
00:27:00  Taking cosmic screenshot
07:09:34  Aborted by …
```

Add timeout to Locate on screen

---

Robot-Framework/resources/gui_keywords.resource
Robot-Framework/resources/setup_keywords.resource
Robot-Framework/test-files/background.config
Robot-Framework/test-suites/gui-tests/__init__.robot

* Use text "Applications" to confirm login instead of the launcher icon. The icon is sometimes missing or hidden.
* Use text "Password" to confirm if lock is active instead of the lock icon. The same lock icon is also used in the power menu so it could cause issues.
* => Icons are now only needed for gui tests.
* Change to gray wallpaper before login and back to default when tests are done. This improves image and text recognition.
* Remove unused `${stop_swayidle}` from `Prepare Test Environment` and from `Log in, unlock and verify`.
* Log device ID at the beginning of the tests.
* Log a proper message when image recognition failed as expected.
* Log gui-vm `systemctl status` before trying to take the first screenshot after login. This could provide useful information if the system gets …

Use text recognition in login and other small changes

---

Robot-Framework/resources/gui_keywords.resource
Robot-Framework/resources/setup_keywords.resource
Robot-Framework/test-suites/gui-tests/__init__.robot

Text `Applications` is not always found when it should be → let’s switch back to launcher icon recognition while I debug the issue.
[Testrun](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/615/)

Back to icons for login

---

Robot-Framework/lib/PerformanceDataProcessing.py

Some performance plots have had legend on the upper right corned which is blocking view to the actual data, especially in VM bar plots. Set legends to upper left corner to see the latest results without disturbing legend on top.
perf run on x1:
https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/695/

Set legends to upper left corner

---

Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/boot-test/boot_test.robot
Robot-Framework/test-suites/boot-test/relay_boot_test.robot
Robot-Framework/test-suites/functional-tests/net-vm.robot
Robot-Framework/test-suites/functional-tests/timesync.robot
Robot-Framework/test-suites/performance-tests/boot_time_test.robot
Robot-Framework/test-suites/performance-tests/network.robot

Development target DEV Orin-AGX Device. 
Network adapters MAC set to match the static IP of DEV Orin- AGX.
Basically what was done was that most of 'IF "Orin-AGX" in ${DEVICE}' were removed and matched to the Lenovo-X1 branch case.
Noticed some failures with RelayBoot tests so added 30s sleep similar to "NX" for 'relayboot_test.robot' & 'boot_test.robot' (IF  "NX" in "${DEVICE}" or "AGX" in "${DEVICE}")
"net-vm" suite - **Took these 3 Orin AGX tests out of execution by commenting out the tags:**, since I think these are not valid when network adapter is used.
- Wifi passthrough into NetVM (Orin-AGX)  (using 'Lenovo test' 'Wifi passthrough into NetVM' -test instead
- NetVM stops and starts successfully
- NetVM is wiped after restarting
**Please let me know if you think …

Refactor code due to taking network adapters into use for AGX devices.

---

Robot-Framework/resources/gui_keywords.resource
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/test-suites/gui-tests/gui_apps.robot
Robot-Framework/test-suites/gui-tests/gui_power_options.robot
Robot-Framework/test-suites/gui-tests/input_control.robot

**Changes**
- Record the screen while GUI test is running and save the video if the test fails. `GUI Log out and log in` is excluded since recording does not work on login screen.
- Small improvement to `Set do not disturb state` to make sure that it immediately closes any open notifications. Setting `do_not_disturb` only stopped new notifications.
**Notes**
- If screen recording fails it will also fail the test case. I have not seen this happen once so I am confident it should not be an issue. If we do see cases where the recording fails, we can switch to `Run Keyword And Ignore Error` when starting/stopping the recording. I would rather not do it right away, it makes noticing potential issues much harder.
**Testruns**
- [Lenovo-X1](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/883/ …

Record GUI tests

---

Robot-Framework/test-suites/performance-tests/network.robot
list_of_skipped_tests.md

Taking network-adapter into use in our test-setup caused some performance measurements to fails.
Some RX results are close to 0.  Of course some kind of different results was expected but nothing this big.
Need to study/understand what might cause the big difference in results.
Taking network tests temporarily out form AGX (tags removed), in order to reduce noise around failures in perftest pipeline.

Remove AGX tags from network tests

---

Robot-Framework/lib/PerformanceDataProcessing.py
Robot-Framework/lib/performance_thresholds.py
Robot-Framework/test-suites/performance-tests/parallel_cpu_test
Robot-Framework/test-suites/performance-tests/performance.robot

Measure cpu resource isolation level by running cpu test in single vm and parallel in two vms. Calculate the
difference.
I tested it locally on Lenovo-X1 and got results ranging from 11% to 18%. 
Test run on Dell shows much higher impact because on that device there is only 8 harware cpus and 8 threads (while X1 has 12 cores / 20 threads) and all 21 virtual vcpus are shared among only 8 threads. So on Dell the VMs overlap on physical cpus is naturally higher.
https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/927/

Add parallel sysbench cpu test

---

Robot-Framework/test-suites/functional-tests/gui-vm.robot
list_of_skipped_tests.md

Skipping Falcon AI test from Lenovo-X1& Darter-Pro.
Test run: [Dev#1054](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1054/)

Skip Falcon AI test

---

Robot-Framework/test-suites/security-tests/ip_spoofing_test.robot
Robot-Framework/test-suites/security-tests/nc_client
Robot-Framework/test-suites/security-tests/nc_server
Robot-Framework/test-suites/security-tests/nc_stealer

- Add delays
- Exit stealer VM before stealer script starts executing
- Add test timeout
- Tune the number of iterations and sleeps
With old ghaf image without ipspoofing protection
https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1238/
With current ghaf mainline
https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1235/

Prevent ipspoof test stuck

---

Robot-Framework/lib/PerformanceDataProcessing.py

Currently build_type gets always value "packages" in the runs which have image url defined or include building the image. In the manual runs where url is not defined and the device is booted from an existing image build_type gets directly the device tag.
Modify initialization of self.build_type so that it gets something more reasonable:
- builder architecture if job variable includes full target name (e.g. packages.x86_64-linux.system76-darp11-b-debug)
- "unknown" if job variable includes only device tag
Test with only device tag, no image url given
https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1377/
("Build type: unknown" in the plot titles.)
Test with image url defined
https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1378/
("Build type: unknown" in the plot titles.)
If …

Show correct string as build type

---

Robot-Framework/test-suites/gui-tests/input_control.robot
list_of_skipped_tests.md

Skip for 'Control audio volume with keyboard shortcuts'.
'Lenovo-installer' -image gets into some unknown state after the device has been suspended. 
In nightly run 'suspension test' is executed before 'Control audio volume with keyboard shortcuts' -test and latter test fails.
Tested locally:
[lenovo_installer_volume_fail_log.html](https://github.com/user-attachments/files/22515041/lenovo_installer_volume_fail_log.html)
[volume_pass_log.html](https://github.com/user-attachments/files/22515042/volume_pass_log.html)

Skip audio volume test (lenovo installer)

---

Robot-Framework/resources/gui_keywords.resource
Robot-Framework/test-suites/suspension-test/suspension.robot

Suspension is disabled on Darter Pro, but we can still test the automatic lock.
To be merged after release has been done.
[Testrun](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1363/)

Add lock test to Darter Pro

---

Robot-Framework/resources/device_control.resource
Robot-Framework/resources/setup_keywords.resource
Robot-Framework/resources/ssh_keywords.resource
Robot-Framework/resources/virtualization_keywords.resource
Robot-Framework/resources/wifi_keywords.resource
Robot-Framework/test-suites/functional-tests/__init__.robot
Robot-Framework/test-suites/functional-tests/apps.robot
Robot-Framework/test-suites/functional-tests/audio.robot
Robot-Framework/test-suites/functional-tests/business-vm.robot
Robot-Framework/test-suites/functional-tests/gui-vm.robot
Robot-Framework/test-suites/functional-tests/host.robot
Robot-Framework/test-suites/functional-tests/logging.robot
Robot-Framework/test-suites/functional-tests/net-vm.robot
Robot-Framework/test-suites/functional-tests/optee.robot
Robot-Framework/test-suites/functional-tests/shares.robot
Robot-Framework/test-suites/functional-tests/timesync.robot
Robot-Framework/test-suites/functional-tests/video.robot
Robot-Framework/test-suites/functional-tests/vm.robot
Robot-Framework/test-suites/gui-tests/gui_power_options.robot
Robot-Framework/test-suites/performance-tests/performance.robot
Robot-Framework/test-suites/security-tests/ip_spoofing_test.robot

**Changes**
- `Switch to vm` can switch to `net-vm`.
- Replace `Connect to VM`, `Connect to ghaf host` and `Connect to netvm` with `Switch to vm` in regression and GUI tests.
- Rename `${NETVM_SSH}` -> `${NET-VM_GHAF_SSH}` to align with the variable names used for other SSH connections.
- `Connect to VM` makes sure there is an active net-vm connection before connecting to a VM (if there is not it will create it). Consequently, `Switch to vm` keyword can be used even if there is no active net-vm connection beforehand. 
**Testruns**
- [Main pipeline](https://ci-dev.vedenemo.dev/job/ghaf-main/82/)
- Lenovo-X1 [regression & GUI](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1480/)
- Lenovo-X1 [performance](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1481/)
**Future development** …

Allow switching to net-vm

---

Robot-Framework/lib/ParsePowerData.py
Robot-Framework/resources/power_meas_keywords.resource
Robot-Framework/test-suites/gui-tests/gui_power_options.robot
Robot-Framework/test-suites/suspension-test/suspension.robot

Fail suspension test cases if the measured
power does not drop below certain limit during
suspension.
Monitor power longer after automated suspension
(To be done in another PR: check that power consumption does not change
significantly from the level before suspension.)
https://ci-prod.vedenemo.dev/job/ghaf-hw-test-manual/315/

Set limit for power during suspension

---

Robot-Framework/test-suites/functional-tests/host.robot
list_of_skipped_tests.md

QSPI should now be updated to all Lab's Orin-NX and Orin-AGX devices.
Setting ' pre-merge ' tag back to QSPI Check -test  and also removal of temporary skip of that test.
I did not use the original way i.e. setting the pre-merge -tag via Force Tags but just added also the tag directly to the test case.  I thought that next time QSPI version is changed, one just needs to take the tag out of the test case, nothing more.
If that is not Ok, I'll change the PR to use Force Tags- method
[TestRun](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1573/)

Set QSPI Check back to pre-merge set.

---

Robot-Framework/resources/common_keywords.resource
Robot-Framework/test-suites/functional-tests/host.robot

Another try to fix the issue related to systemctl status checks.
- Use `systemctl is-system-running` to get the systemctl status.
- Fix an issue where the host systemctl status check was skipped if `systemctl status` command timed out.
[Lenovo-X1](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1599/)
[Orin-AGX](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1600/)

Use is-system-running to check status

---

Robot-Framework/test-suites/functional-tests/host.robot
Robot-Framework/test-suites/functional-tests/vm.robot
list_of_skipped_tests.md

Check the host systemctl status as part of `Check systemctl status in every VM` for laptop targets. Orins still use `Check host systemctl status`.
[Lenovo-X1](https://ci-dev.vedenemo.dev/job/ghaf-hw-test-manual/1633/)

Check host systemctl status in vm tests
